name: Label Based PR Policy Action
author: C.M.P.Soares Lda. <contact@cmpsoares.com>
description: This Github Action will require a minimum number of reviews and/or specific check-runs are successful if a label is present.
runs:
  using: 'node12'
  main: 'dist/index.js'

inputs:
  github_token:
    description: 'Github token to authenticate Octokit'
    required: true
# TODO: Create the timeout inputs
branding:
  icon: 'git-pull-request'  
  color: 'green'

