name: "Building the Code"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
